services:
  - type: web
    name: online-test-system-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false